### ISSUE TITLE
Scraping /metrics endpoint triggers a local execution of bmc-info, ipmimonitoring

### ISSUE THREAD

**Issue by dswarbrick** [soundcloud/ipmi_exporter#33]
We are interested in running ipmi_exporter in VMs and using it to probe multiple remote hosts via the LAN_2_0 driver.

I have noticed that when scraping the `/metrics` endpoint, this is triggering an unwanted execution of bmc-info and ipmimonitoring commands. This is obviously not going to work in a VM, which has no IPMI device.
```
Sep 23 14:05:48 ber-prom1 prometheus-ipmi-exporter[5796]: time="2019-09-23T14:05:48Z" level=error msg="Error while calling bmc-info for [local]: hostname not specified\n" source="collector.go:235"
Sep 23 14:05:48 ber-prom1 prometheus-ipmi-exporter[5796]: time="2019-09-23T14:05:48Z" level=error msg="Error while calling ipmimonitoring for [local]: hostname not specified\n" source="collector.go:235"
Sep 23 14:05:48 ber-prom1 prometheus-ipmi-exporter[5796]: time="2019-09-23T14:05:48Z" level=error msg="Failed to collect ipmimonitoring data from [local]: exit status 1" source="collector.go:397"
```

As far as I can tell, it's due to the fact that the main function registers a collector, which is going to be invoked by `promhttp.Handler` whenever the `/metrics` endpoint is hit.
```go
	localCollector := collector{target: targetLocal, module: "default", config: sc}
	prometheus.MustRegister(&localCollector)

	http.Handle("/metrics", promhttp.Handler())       // Regular metrics endpoint for local IPMI metrics.
```

I'm not sure if the ramifications of this were fully considered. To compare with blackbox_exporter, which is a similar design pattern, I would say it is probably _not_ intended, since scraping blackbox_exporter's `/metrics` doesn't trigger any probes as such.

Perhaps this local probe could be made optional?

**Comment by bitfehler** [comment]
Hi, thank you for your report! However, I am not sure I fully understand your use case.

If you want to scrape remote hosts, you need to call the `/ipmi` endpoint with a `target` parameter, not the `/metrics` endpoint (see https://github.com/soundcloud/ipmi_exporter#remote-metrics). The `/metrics` endpoint is for folks who prefer to run the exporter on the very hosts they want to monitor.

If you really do want to monitor the local exporter instance, I would be very interested to know why you would like to do so, as this is indeed a case that has not really been considered so far. All you get is few standard Go metrics. For example in our production setup, we do not monitor the `/metrics` endpoint of our exporter instances at all. We only scrape remotely and the service monitoring is better done by the OS.

And, last but not least, if you really want that data, there is a way you can achieve this: the local scrape is always performed with the `default` module. As such, you can set the following config for the `default` module: `collectors: []` - this way it will not run any of the collectors. Of course then you would have to make sure to not use the `default` module for any of your remote targets.

Please let me know if any of this is helpful. Otherwise please try to elaborate a bit on your setup.

**Comment by dswarbrick** [comment]
ipmi_exporter is being launched with `--config.file=/etc/prometheus/ipmi_remote.yml`, which simply contains the fullowing:
```yaml
modules:
  default:
    user: MONITOR
    pass: <secret>
    driver: LAN_2_0
    privilege: user
    timeout: 10000
    collectors:
    - bmc
    - ipmi
```
The main Prometheus job for probing remote IPMI hosts is as follows:
```yaml
- job_name: ipmi
  scrape_interval: 1m
  metrics_path: /ipmi
  file_sd_configs:
  - files:
    - targets/ipmi.yml
  relabel_configs:
  - source_labels: [ipmi_module]
    target_label: __param_module
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: localhost:9290
```
The `ipmi_module` label is sourced from the targets yaml, so that we can potentially have different targets use a different module. That all works as expected.

We have a second job to actually scrape the internal metrics of ipmi_exporter, which is what appears to be trying to trigger a _local_ execution of freeipmi:
```yaml
- job_name: ipmi-metrics
  static_configs:
  - targets:
    - localhost:9290
```
My assumption is that this would work like the `/metrics` endpoint of blackbox_exporter, whereby you can record stats about number of probes executed, etc.

However, since ipmi_exporter's handler for the `/metrics` endpoint has the local collector registered, the local freeipmi execution is _also_ triggered, when in fact we're really only interested in the internal metrics of the exporter.

**Comment by bitfehler** [comment]
Thanks for the clarifications, I think I understand now.

> My assumption is that this would work like the `/metrics` endpoint of blackbox_exporter, whereby you can record stats about number of probes executed, etc.

It doesn't really, the IPMI exporter's `/metric` endpoint is intended for scraping the IPMI device of the host that the exporter is running on. Also, there currently simple are no aggregate metrics like that collected at all. All you'd get is the Go runtime stats and the standard process metrics described [here](https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics). For scrape failures and timing, you should track the `ipmi_up` and `ipmi_scrape_duration_seconds` metrics from the `/ipmi` endpoint. They are much more useful as you can drill down by target and collector.

That said, my statement from above still applies: if you do think the local process metrics are of value to you, try the following config (it's your config from above but slightly adapted):

Your `ipmi_remote.yml`:
```
modules:
  default:
    collectors: []
  remote:
    user: MONITOR
    pass: <secret>
    driver: LAN_2_0
    privilege: user
    timeout: 10000
    collectors:
    - bmc
    - ipmi
```
Then, make sure your target file, `targets/ipmi.yml`, looks something like this:

```
---
- targets:
  - ...
  labels:
    job: ipmi_exporter
    module: remote
```
The important part being that you scrape the remote targets with the `remote` module, and that the `default` module is configured with `collectors: []`. Now the local scrape will not run any of the IPMI collectors.

If you try this setup, I would be interested if you find the metrics you get there useful in any way. Also, if not, what where you hoping to find that you cannot derive from the remote metrics?

This made me realize that the README maybe needs a bit of lovin' with regards to modules. I might also point out more how the IPMI exporter is different in this regard from the blackbox exporter, as I now understand the angle you were coming from.

Let me know how this turns out.
